---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surrealdb
  namespace: {{ .Release.Namespace }}
  {{- if .Values.commonLabels }}
  labels: {{- toYaml .Values.commonLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: surrealdb
  template:
    metadata:
      labels:
        app: surrealdb
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels  }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations: {{ toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: surrealdb
          image: {{ include "surrealdb.image" . }}
          imagePullPolicy: {{ include "surrealdb.imagePullPolicy" . }}
          args:
            - start
          env:
            - name: DB_PATH
              value: {{ include "surrealdb.database" . | quote }}
            - name: USER
              value: {{ include "surrealdb.username" . | quote }}
            - name: PASS
              value: {{ include "surrealdb.password" . | quote }}
            - name: LOG
              value: {{ include "surrealdb.loglevel" . | quote }}
          ports:
            - name: http
              containerPort: 8000
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /data
              name: surreal-data
              # subPath: data
          startupProbe:
            tcpSocket:
              port: http
            failureThreshold: 20
            initialDelaySeconds: 3
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: surreal-data
          {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
