---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surrealdb
  namespace: {{ .Release.Namespace }}
  {{- if .Values.commonLabels }}
  labels: {{- toYaml .Values.commonLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.pod.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        {{- if .Values.pod.labels }}
        {{ toYaml .Values.pod.labels  }}
        {{- end -}}
      {{- if .Values.pod.annotations }}
      annotations: {{ toYaml .Values.pod.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.pod.affinity }}
      affinity: {{- toYaml .Values.pod.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.pod.tolerations }}
      tolerations: {{- toYaml .Values.pod.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: surrealdb
          image: {{ include "surrealdb.image" . }}
          imagePullPolicy: {{ include "surrealdb.imagePullPolicy" . }}
          args:
          - start
          env:
          - name: DB_PATH
            value: {{ include "surrealdb.database" . }}
          - name: USER
            value: {{ include "surrealdb.username" . }}
          - name: PASS
            value: {{ include "surrealdb.password" . }}
          - name: LOG
            value: {{ include "surrealdb.loglevel" . }}
          {{- if .Values.pod.env }}
          {{- toYaml .Values.pod.env | nindent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8000
          {{- if .Values.pod.resources }}
          resources: {{- toYaml .Values.pod.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /data
              name: surreal-data
              # subPath: data
          startupProbe:
            tcpSocket:
              port: http
            failureThreshold: 20
            initialDelaySeconds: 3
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: surreal-data
          {{- if and .Values.pod.persistence.enabled .Values.pod.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.pod.persistence.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
